# Generated by Django 5.0.1 on 2024-01-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='entrou_em',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='telefone',
            field=models.IntegerField(null=True),
        ),
    ]
